### ISSUE TITLE
Library loading for Windows and Mac

### ISSUE THREAD

**Issue by jesserayadkins** [jesserayadkins/lily#116]
The current library loading code needs to be ported to Windows and possibly touched up for Mac as well. It may also be necessary to fix up the code that determines the namespace of a file to work with Windows filenames if on Windows.

**Comment by kainjow** [comment]
FWIW, I built the project successfully on OS X using Unix Makefiles and Xcode generators. But that doesn't necessarily means it works. You should consider implementing Travis and Appveyor support.

**Comment by jesserayadkins** [comment]
I'd like to have some CI support, eventually. Making sure that all tests pass and that I don't introduce any regressions is really important to me. It will probably be a while before I get to that though, as my current mindset is to focus more on core features in hopes of bringing in contributors/users eventually.

**Comment by jesserayadkins** [comment]
When I added this issue, it was because libraries were loaded from a set of paths like `/usr/lib/lily` and there was no equal for Windows. There was also no port for Windows at that time. Now that loading is relative and there is a port to Windows, I think loading now works acceptable on all platforms. If I'm wrong, then this can be reopened or a new issue filed.

**Comment by kainjow** [comment]
You can add OS X support to Travis to verify by adding `- osx` after the linux line in .travis.yml
