### ISSUE TITLE
Naming consistency

### ISSUE THREAD

**Issue by AndrewCarterUK** [jesserayadkins/lily#168]
Hello,

Saw this posted on reddit and thought I'd give some feedback. Is there any reason for the apparent difference in naming convention between `Either.is_left` and `File.readline`? Shouldn't it be `File.read_line`?

Same reasoning applies to `String.endswith`, `String.htmlencode`, `String.isspace` etc.

It seems trivial but a big problem for me with PHP is continually having to lookup functions - even though I can remember their names - because I can't remember whether and where underscores are used or parameter order differs.

Thanks,

Andrew

**Comment by jesserayadkins** [comment]
You're absolutely right. This was an oversight on my part: When I first added the functions in, I added in Python's name (which don't include underscores) and then later used Ruby as a model for collection methods (and those do have underscores). It should be underscores everywhere.
