### ISSUE TITLE
Rewindability

### ISSUE THREAD

**Issue by jesserayadkins** [jesserayadkins/lily#174]
If you feed a chunk of code to the interpreter, and that chunk fails to interpret, then the interpreter is left in an undefined state. This is a problem:

* You can't embed the language as a runtime script language, because the parser becomes effectively broken if it fails

* A repl is not possible, because a broken script may leave globals/functions/classes/etc. around when it shouldn't.

These two cases are interesting because they have different wants. An embedded language will want to take a given script and rollback everything. A repl, on the other hand, might want to carry on if the current expression is incomplete (this is how Lua's repl works), or rollback (if the code is broken).

Regardless, there's a fair amount of work involved in rolling back the interpreter. Import usages must be pulled back. If the main file loads an import, and that import is broken, then that import also needs to be undone. Classes need to be rewound, id's scaled back, etc., etc.

My approach to Lily thus far has been to reuse whatever is available again in some way. However, I feel that rewinding should free and later re-create imports/classes/etc. Some might argue that this might be expensive, memory-wise, to recreate the data again. My counter argument to that would be that repeatedly sending broken scripts might be a way to get the interpreter to retain structures that it wouldn't be able to get rid of (ex: creating a ton of classes in a broken script).

**Comment by jesserayadkins** [comment]
I'm removing this from the next release because there's simply too much to be done properly between now and Lily's 5 year mark. I could do this, but only by slicing far too many corners to be comfortable with that.

**Comment by jesserayadkins** [comment]
I've just now pushed a new branch, rewind, that I'll be pushing bits and pieces of rewind as I go along. I think the interpreter is finally ready for this.

**Comment by stevedonovan** [comment]
Ah, so a REPL is one good thing that will emerge from this. REPLs are nearly always a good thing, especially for exploration - and all users start by exploring (well, this user does)

**Comment by stevedonovan** [comment]
whoops, I get after pulling & cmake:
```
/home/steve/projects/scratch/dev/lily/src/lily_parser.c:81:11: error: ‘lily_parse_state’ has no member named ‘old_module_start’
     parser->old_module_start = NULL;
           ^
```

**Comment by jesserayadkins** [comment]
Sorry about that. I forgot to enable the pre commit tests again on my side. I fixed it though, I think.

**Comment by stevedonovan** [comment]
Can confirm that it builds fine now. Very curious to see that REPL when you
get around to it!
