### ISSUE TITLE
Problems with 32-bit Linux (Ubuntu)

### ISSUE THREAD

**Issue by stevedonovan** [jesserayadkins/lily#203]
```
try$ lily show_classes.lly 
Created three Points: ["Point(5, 10)", "Point(40, 500)", "Point(11, 2)"]
How many coordinates have an x < y? : 2
Using Point.moveBy to move each X down by half...
Points are now: ["Point(3, 10)", "Point(20, 500)", "Point(6, 2)"]
*** Error in `lily': free(): invalid pointer: 0x08abb180 ***
Aborted (core dumped)
try$ uname -a
Linux xubuntu 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:08:14 UTC 2014 i686 i686 i686 GNU/Linux
```
This also happened for the combine-functions example.

32-bit Linux is still popular with embedded devices, so this can be important.

**Comment by jesserayadkins** [comment]
It's been a while since I've used 32-bit Linux. I'd like to get this fixed though, because these issues are likely to manifest when trying to port to Arduino (which I've heard has 16-bit pointers).

**Comment by stevedonovan** [comment]
Cool - all examples and top-level tests pass!
