### ISSUE TITLE
Scope lookup issue with function declarations

### ISSUE THREAD

**Issue by stevedonovan** [jesserayadkins/lily#207]
```
C:\me\dev\lily>copy con bug2.lly
var a = 10
define make_pair[A,B](a: A, b: B): Tuple[A,B]
{
   return <[a,b]>
}
print (make_pair("answer",42))
^Z
        1 file(s) copied.

C:\me\dev\lily>lily bug2.lly
SyntaxError: a has already been declared.
    from bug2.lly:2
```
Will work fine if we don't call the argument `a`.

**Comment by jesserayadkins** [comment]
I think this one is right though. If make_pair is allowed to use `a` as a parameter, then it shadows the declaration of the global `a`.

**Comment by stevedonovan** [comment]
It did come as a surprise because argument lists are effectively local variables. But if there's a no-shadow-rule then it's appropriate. Globals should have a lot more letters than 'a'.
