### ISSUE TITLE
Is there a repo with the tutorial.html?

### ISSUE THREAD

**Issue by radiofreejohn** [jesserayadkins/lily#208]
I want to submit a fix to one of the examples. It's OK if there's no repo, the example is this one:

```
var does_end = String.ends_with("needle", "e")
does_end = "needle".ends_with(e)
does_end = "e" |> "needle".ends_with
```

I think the second version needs quotes around the `e`:

```
does_end = "needle".ends_with("e")
```

**Comment by Jan-Kow** [comment]
@radiofreejohn
Here you go https://github.com/jesserayadkins/lily/blob/gh-pages/tutorial.html :)

**Comment by radiofreejohn** [comment]
I didn't think to check the branches, thanks!
