### ISSUE TITLE
"The closest that any other interpreted language comes to this is Lua, which boots in 30K (over 4x as much!)."

### ISSUE THREAD

**Issue by pfalcon** [jesserayadkins/lily#209]
Really? MicroPython https://github.com/micropython/micropython in its default config can do that in less than 2K:

~~~
$ micropython -X heapsize=1700
MicroPython v1.8.1-173-g4cfe3e8 on 2016-07-02; linux version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> print("Hello World")
Hello World
~~~

And then it's an implementation of a large subset of a well-known language, not a custom one.

**Comment by Jan-Kow** [comment]
I don't want to offend you but in my opinion this is not the right place to discuss this stuff. Checkout the IRC or the [reddit post](https://reddit.com/r/programming/comments/4qs56m/lily_programming_language/) where some of questions like this (I have seen) are already answered :)

**Comment by jesserayadkins** [comment]
I'll be removing this remark when I get the time. Someone has already mentioned Forth, and now this. I think the best solution is to remove it, and just focus on how Lily tries to cut memory use rather than claims like this (which may not even stand if other languages put in similar strategies to dynaload or cut their own memory use).

**Comment by pfalcon** [comment]
No problem guys, just as a Lua-hater I couldn't pass by it still being used as a reference in 2016 :-D. (There's also a bit of programming (socio)psychology - I always wonder what drives people who design their own programming languages, common sense says they won't be used by many other people, i.e. are bound to decline and die; there must be a particular reason why this is done, and efficiency is one which resonates with my own feelings very well; god I'm happy I work on a both efficient and generally popular language. Nevermind the philosophy.).
