### ISSUE TITLE
Feature Request: Allow initialization of enum values with matching expressions

### ISSUE THREAD

**Issue by stevedonovan** [jesserayadkins/lily#219]
I'm not sure about the title, but here is the need:  there is no function overloading, and that IHMO is a good thing. We can always use `Either[A,B]` to give functions more flexible arguments. Say I have `define boo(a: Either[String,Integer])`.  Currently it must be called with explicit values, e.g. `boo(Left("hello"))`.  It would be _so_ convenient that in cases where the types are unambiguous we could say `boo("hello")` or `boo(42)`.

Obviously each value of the enum must have different types for this to work, but the shortcut seems harmless and perfectly type-safe.

**Comment by jesserayadkins** [comment]
I'm not so sure about this:

First, what happens for enums that have variants with multiple arguments, but where the different variants all happen to be unique to each other? Does this not work, or does it get special rules to accommodate?

I can see this leading to a codebase that has a mixture of both: Sometimes implicit, sometimes explicit enum usage.

I can see this having some pitfalls...like if there's an `Either` that has two functions to it and both are good matches, and trying to pick a 'best' one.

I'm not absolutely against it, but I'm hard pressed to add it as I don't currently see the value of it.

**Comment by stevedonovan** [comment]
It is obviously a special case, since variants with multiple arguments cannot participate in such a scheme. 

The 'best match' problem would be solved by insisting on strict unambiguous type matching.

But here is the real motivation: with a little work, we can get clean type-safe JSON literals.

```
var j = [
   "alpha" => [1.0,2.0],
  "beta" => [
     "arg0" => 10.0,
     "arg1" => 20.0
  ]
]
```
This is a recursive enum, because some of the variants refer to the enum itself. Leads itself to very nice pattern matching.

Of  course, this can lead to inconsistent style; I suppose I'm so used to C++, where it's considered pedantic to say `foo(std::string("hello"))` where `foo("hello")` does just as well due to a suitable constructor being available.  So it can be reframed as being about conversion through constructors.

It boils down to how much sugar you like in your diet, I suppose ;)

**Comment by stevedonovan** [comment]
Just noticed your `show_off_enums` example which is exactly where the sugar would make things cleaner. But I accept that it _is_ sugar. 

Logically it would also allow an argument of `["Felix","Ginger"]` to a function expecting `List[Cat]`, assuming `Cat` had a constructor from `String`.

**Comment by stevedonovan** [comment]
Ah, not too bad ;)

```C
enum JsonObject {
    JS(String)
    JN(Double)
    JA(JsonObject...)
    JO(Hash[String,JsonObject])

    define as_str: String {
       match self: {
       case JS(s):
          return $"\"^(s)\""
       case JN(n):
          return $"^(n)"
       case JA(l):
          var out = l.map{|v| v.as_str() }.join(",")
          return $"[^(out)]"
       case JO(m):
          var out: List[String] = []
          m.each_pair {|k,v| out.push($"\"^(k)\":^(v.as_str())") }
          var str = out.join(",")
          return $"{^(str)}"
       }
    }


}

var j = JO([
        "one" => JS("hello"),
        "two" => JN(23.0),
        "three" => JA(JS("3a"),JS("3b"))
])

print(j.as_str())
==> {"three":["3a","3b"],"two":23,"one":"hello"}
```
(Does github understand lily yet?)

**Comment by jesserayadkins** [comment]
Type-safe json literals are pretty compelling, I have to admit. I worry about doing this now, for fear of this not having much use outside that. Your example works, though I much prefer the implicit approach.

I'll keep this in mind for later. At the moment, I'm overly conservative since I don't want any accidents.

It does not, yet. I'll take a look into seeing what that would entail, because I'm now curious.

**Comment by stevedonovan** [comment]
Yes, best to keep things simple and explicit. One less thing to remember, and it seems silly to have a _language feature_ for a narrow set of use cases.
