### ISSUE TITLE
Compiler bug with expressions within classes

### ISSUE THREAD

**Issue by stevedonovan** [jesserayadkins/lily#232]
```c
class Alpha(s: String) {
   var @s = s
   define upper: String {
      return @s.upper()
   }
}
class Beta(s: String) {
   var @a = Alpha(s)
   var @b = @a.upper()
}
var b = Beta("hello")
```
Call to `String.upper` blows up, and my friend GDB tells me that the string passed as self to this method is garbage:
```c
(gdb) p *input_arg->value.string
$3 = {refcount = 5, size = 25, string = 0x2 <error: Cannot access memory at address 0x2>}
```
It appears not to be peculiar to 'constructor' scope, since if I don't define `b` and instead within `Beta` define:
```
   define upper: String {
      return @a.upper()
   }
```
We get a similar crash when `Beta.upper` is called.

So I make this method more explicit:
```
      var str = @a.s
      print(str)
      return str.upper()
```
Same kind of crash in `String.upper`, but the output is "<.Beta at 0x642230>" !

**Comment by stevedonovan** [comment]
The problem is when a class is created in the compiler context. If I just  give in and pass an existing instance of `Alpha` to `Beta`, then everything works well.

**Comment by jesserayadkins** [comment]
Saw this just now and thought I'd take a swing at it. Alpha is being tagged as needing a gc marker, and is somehow being collected. If you remove the method call, that part should be okay.

As for the corrupt output, that might be related to #186, and thus might be solved when I put in new stack api. I haven't tested that idea yet though.

Regardless of Alpha being gc tagged, it shouldn't be getting destroyed.

**Comment by jesserayadkins** [comment]
I deleted my comment because it had a bunch of incorrect speculation. Sorry about that. I should have seen the problem wasn't the vm from the beginning.

The reason you're getting refcount 5, size 25 is because the value you're dealing with is not a string, but an instance! 25 is where user-defined classes start off at.

This smells like an emitter bug.
