### ISSUE TITLE
Easy ideas for dyna_tools.py

### ISSUE THREAD

**Issue by jesserayadkins** [jesserayadkins/lily#244]
`dyna_tools.py` is useful, but the interface of it could use some attention. What I'm proposing won't touch the guts of the script, and it's doable with not a lot of Python knowledge.

First, the invocation needs to change:

`dyna_tools.py new package <package name> <path>`. This reads `<path>`, and processes the comments inside of it. The result is a dynaload table.

`dyna_tools.py new embedded package <package name> <path>`. This reads `<path>`, and always generates a dynaload table, and a loader.

`dyna_tools.py refresh <path>` Reads from `<path>`, and determines what needs to be generated. Whatever was generated before is updated. This is to make it easy to say, for example, `dyna_tools.py refresh src/lily_pkg_sys.c`, and not have to worry about how the sys package works.

`dyna_tools.py html <path>` Reads from `<path>` for comments and generates html documentation.

What's changing where the generated data is put. The data generated should be placed into a file, and `#include`ed into the main file. This has the secondary effect of making for cleaner diffs later on (dynaload regeneration will show up in a diff to another file). The file name picked should be based on the file provided (dyna_$NAME.c, perhaps).

If anyone is interesting in taking this up, it would be a big help. If not, I'll get around to it in a week or two.

**Comment by stevedonovan** [comment]
Ah, now I understand, after playing with the script - the loader is the function that returns the function pointers from an embedded file.  Your proposed subcommand renaming makes much more sense now.

**Comment by jesserayadkins** [comment]
The terminology needs some explaining within the script too. I suspect new users may not know what they'll need at first. But that's a big reason why I want a 'refresh' option that acts as a magic wand to automatically fix it. That way, someone can come in, make a few changes, and do a sort of F5/refresh. I'll handle auto-generating documentation at a later time.

**Comment by jesserayadkins** [comment]
I'm taking this because I'm working with dyna_tools.py right now to get it to understand enums and variants, and also to be more clean inside. I haven't pushed the changes, but fixing what needs to be fixed won't be that hard, so I might as well do it now.
