### ISSUE TITLE
Unclear error message: "SyntaxError: A class with the name '' already exists."

### ISSUE THREAD

**Issue by a-p-** [jesserayadkins/lily#246]
This code:

    enum Test[A] {
        A(A)
    }

causes lily (1df03d72ab747f1fc4d4c927e06e56cf1363d82a) to give an error message like:

    $ ../../build/lily enum-name-empty.lly 
    SyntaxError: A class with the name '' already exists.
        from enum-name-empty.lly:2
    $ 

The "... the name '' ..." part is kind of unclear.

**Comment by a-p-** [comment]
This code also gives a similar error message with an empty-string name:

    class Test[A] < A
    {
    }

like:

    $ ../build/lily name.lly
    SyntaxError: '' cannot be inherited from.
        from name.lly:1
    $

**Comment by jesserayadkins** [comment]
Generics are implemented as a class that doesn't have a name. Instead, their name is drawn from their identity. It's not a good system, and I've been wanting to redo it for a while. I'll look into it after writing the API (of which the hard part is now done!). I'll fix this anyway in the meantime.
