### ISSUE TITLE
Unclear error message: "SyntaxError: Wrong number of arguments to Test.test (2 for 1)."

### ISSUE THREAD

**Issue by a-p-** [jesserayadkins/lily#247]
Code like:

    class Test
    {
        define test
        {
        }
    }

    var test = Test()
    test.test(123)

causes lily (1df03d72ab747f1fc4d4c927e06e56cf1363d82a) to give an error message like:

    $ ../../build/lily param-numbering.lly 
    SyntaxError: Wrong number of arguments to Test.test (2 for 1).
        from param-numbering.lly:9
    $

Although the `Test.test` method has 0 explicit parameters, and only 1 argument is being passed when calling it, the error message suggests 2 arguments are being passed when only 1 is expected.

Guess it's probably the implicit `self` parameter that's causing the counts in the error message to be higher?

Found it mildly confusing that the error message counts didn't match up with what the code is showing, though.

**Comment by jesserayadkins** [comment]
It's implicit self at work. Rewriting your example a touch.

```
class Test
{
    define method
    {
    }
}

var x = Test()
x.method(123)
```

`x.method(123)` is equal to `Test.method(x, 123)`. So you're passing two arguments because of an implicit self.

For the method itself, it takes one argument because of an implicit self that's passed.

It seems weird, but it's entirely implicit self at work.

I'd like to help, but I'm at a loss as to what to change the message to (I like the consistency of the x for y in errors).

**Comment by a-p-** [comment]
Okay, thanks, I see.

Since `self` is implicit, rather than being specified when defining the method, I suppose I wasn't really considering it to be a parameter of the method, at least from my perspective as a user of Lily.

I was initially expecting an error message along the lines of what C++ compilers show for similar code, where the `this` pointer is implicit, like:

    class Test
    {
        public:
            void method(void)
            {
            }
    };

    void test(void)
    {
        Test x;
        x.method(123);
    }

For example, Clang gives:

    test.cxx:12:11: error: too many arguments to function call, expected 0, have 1

and GCC gives:

    test.cxx:4:8: note:   candidate expects 0 arguments, 1 provided

So I was initially thinking a message like:

    SyntaxError: Wrong number of arguments to Test.method (1 for 0).

would better match what the code is showing (i.e. 0 explicit parameters for Test.method, while 1 argument is wrongly passed when calling it.)

I could see the current "2 for 1" message being clearer if `self` were explicitly included when defining the method, like in Python:

    class Test:
        def method(self):
            pass

    x = Test()
    x.method(123)

where it gives:

    TypeError: method() takes 1 positional argument but 2 were given

**Comment by jesserayadkins** [comment]
Seeing what C++ compilers do for the issue makes it make more sense. So if it's being invoked as a method (oo_access, I think it's called), then subtracting 1 from the counts on both sides to account for an implicit self. Yeah, that makes sense.
