### ISSUE TITLE
Unclear error message: "SyntaxError: Statement(s) after 'return' will not execute."

### ISSUE THREAD

**Issue by a-p-** [jesserayadkins/lily#249]
Code like below, which was intended to return a value but where the function's return type was accidentally omitted:

    define test { return 0 }

causes lily (1df03d72ab747f1fc4d4c927e06e56cf1363d82a) to give an error message like:

    $ ../../build/lily return.lly 
    SyntaxError: Statement(s) after 'return' will not execute.
        from return.lly:1
    $

It runs without giving an error message after specifying the function's return type:

    define test: Integer { return 0 }

Maybe that error message should hint that the function's return type might be unintentionally missing?

Was also initially confused by how it refers to "Statements(s) after 'return'", although in a case like this the return statement is the last one. Guess I was considering the return's expression to be part of the return statement itself, rather than a separate statement following it.

**Comment by stevedonovan** [comment]
I hit that one today ;)

**Comment by jesserayadkins** [comment]
I've hit this a couple of times in the past, but wasn't sure what a good terse error message would be. How about `"(Missing return?) Statement(s) after 'return' will not execute."`, with the aim being that parentheses at the front draws the attention toward the problem?

**Comment by Jan-Kow** [comment]
What's with ``'return' used but no function return type specified (given: int, wanted: null)``?

**Comment by jesserayadkins** [comment]
I'm not so sure about that. `return` is okay when there isn't an explicit value to send back. It could be an early exit from a function returning nothing, for example.

**Comment by Jan-Kow** [comment]
Oh, I understand. Then what's with ``Statement(s) after 'return' will not execute when no function return type is given.``?

**Comment by jesserayadkins** [comment]
I like the direction of that. I think `Statement(s) after 'return' will not execute (no return type given)` will do. Similar, but with that extra bit at the end to draw attention.
