### ISSUE TITLE
Hint about possibly-omitted "var" keyword for assignments to unknown properties?

### ISSUE THREAD

**Issue by a-p-** [jesserayadkins/lily#258]
I've found myself accidentally writing code like this on several occasions:

    class Test(xyz: Integer)
    {
            @xyz = xyz
    }

where the `var` keyword is accidentally omitted before the `@xyz = xyz` assignment.

Lily (4973a917612c85f24be2f852af2f75f0f2722cad) gives an error like:

    $ ../lily var.lly 
    SyntaxError: Property xyz is not in class Test.
        from var.lly:3
    $ 

I find that it isn't immediately obvious that it's the missing "var" keyword that's causing the error.

For assignments to an unknown property like that, maybe the error message could hint that the "var" keyword may be missing, perhaps something like:

    SyntaxError: Property xyz is not in class Test. ('var' keyword may be missing.)

**Comment by jesserayadkins** [comment]
Seems reasonable and consistent with the return missing a type message.
