### ISSUE TITLE
Unexpected behaviour for object property assignments.

### ISSUE THREAD

**Issue by a-p-** [jesserayadkins/lily#260]
Code like:

    class Test[A](name: String, left: A, right: A) {
        var @name = name
        var @left = left
        var @right = right

        define output {
            print("----")
            print(self)
            print(@name)
            print(@left)
            print(@right)
        }
    }

    var a0 = Test("a0", 0, 0)
    var a1 = Test("a1", 1, 1)
    var b = Test("b", a0, a0)
    var c = Test("c", a1, a1)

    print("==== BEFORE ====")
    a0.output()
    a1.output()
    b.output()
    c.output()

    b.@left = c
    c.@right = b

    print ("\n==== AFTER ====")
    a0.output()
    a1.output()
    b.output()
    c.output()

results in output like (with lily 4973a917612c85f24be2f852af2f75f0f2722cad):

    ==== BEFORE ====
    ----
    <Test at 0x7f94a1405b90>
    a0
    0
    0
    ----
    <Test at 0x7f94a1405c20>
    a1
    1
    1
    ----
    <Test at 0x7f94a1405cb0>
    b
    <Test at 0x7f94a1405b90>
    <Test at 0x7f94a1405b90>
    ----
    <Test at 0x7f94a1405d40>
    c
    <Test at 0x7f94a1405c20>
    <Test at 0x7f94a1405c20>

    ==== AFTER ====
    ----
    <Test at 0x7f94a1405b90>
    a0
    0
    0
    ----
    <Test at 0x7f94a1405c20>
    a1
    1
    1
    ----
    <Test at 0x7f94a1405d40>
    c
    <Test at 0x7f94a1405c20>
    <Test at 0x7f94a1405c20>
    ----
    <Test at 0x7f94a1405d40>
    c
    <Test at 0x7f94a1405c20>
    <Test at 0x7f94a1405c20>

In the "BEFORE" output, there are four distinct objects.

Then some properties of `b` and `c` are assigned to. `b` and `c` themselves aren't assigned to, though.

In the "AFTER" output, `b` appears to be referring to `c`, although `b` itself wasn't assigned to.

Not sure if this is a bug, or just a misunderstanding on my part...

I would have expected `b` and `c` to continue to refer to the original objects, since it was only their properties that were assigned to.

Should those assignments even be allowed? If I'm understanding this correctly, then:

- `a0` and `a1` would have type `Test[Integer]`
- `b` and `c` would have type `Test[Test[Integer]]`
- `b.@left`, `b.@right`, `c.@left`, `c.@right` would have type `Test[Integer]` since they were initialized with `a0` or `a1`

It seems like it shouldn't be possible to assign `Test[Test[Integer]]` values to properties with type `Test[Integer]`?

**Comment by jesserayadkins** [comment]
```
b.@left = c
c.@right = b
```

Huh, I thought I had prevented that. If you do `b.left` and `c.right`, then a syntax error is properly printed.
