### ISSUE TITLE
Crasher: __main__() (need recursion limits)

### ISSUE THREAD

**Issue by FascinatedBox** [jesserayadkins/lily#69]
**main**() causes the interpreter to lock up. The problem is bad enough that I have to kill it through pkill instead of just Ctrl-C. I think this is due to the interpreter not setting a reasonable default recursion limit (my guess is that it's looping and mallocing infinitely because there are no limits).

**Comment by jonathonf** [comment]
Having a hard-coded limit breaks any well-behaved code that relies heavily on recursion - even in tail recursive functions which won't overflow.

For example, the following code will fail to run when trying to calculate any factorial >= 100! (granted `Integer` will overflow at 17! but that's a different issue).

```
define fact_(c: Integer, n: Integer): Integer {
    if n <= 1:
        return c
    else:
        return fact_(c*n, n-1)
}

define fact(n: Integer): Integer {
    return fact_(1, n)
}

print(fact(16))
```

**Comment by FascinatedBox** [comment]
Agreed. The recursion limit should be stored in the vm, and also be configurable, perhaps through `sys` as Python does it.
